# Generated by Django 5.2.5 on 2025-08-11 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_photos/', verbose_name='Фотография')),
                ('status', models.IntegerField(choices=[(0, 'На проверке'), (1, 'Одобрен'), (2, 'Отклонен')], verbose_name='Статус одобрения')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='book_logos/', verbose_name='Обложка')),
                ('symbols', models.IntegerField(blank=True, null=True, verbose_name='Количество символов')),
                ('type', models.IntegerField(choices=[(0, 'Художественная'), (1, 'Нон-фикшн (не художественная)')], verbose_name='Тип')),
                ('status', models.IntegerField(choices=[(0, 'На проверке'), (1, 'Одобрен'), (2, 'Отклонен')], verbose_name='Статус одобрения')),
            ],
        ),
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Начало чтения')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Конец чтения')),
                ('topic', models.TextField(blank=True, null=True, verbose_name='Тема')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('three_sentences', models.TextField(blank=True, null=True, verbose_name='Книга в 3-х предложениях')),
                ('new_knowledge', models.TextField(blank=True, null=True, verbose_name='Новые знания')),
                ('transformed_me', models.TextField(blank=True, null=True, verbose_name='Как книга изменила меня')),
                ('impressions', models.TextField(blank=True, null=True, verbose_name='Впечатления')),
                ('ideas', models.TextField(blank=True, null=True, verbose_name='Основные идеи')),
                ('heroes', models.TextField(blank=True, null=True, verbose_name='Герои')),
                ('begin', models.TextField(blank=True, null=True, verbose_name='Начало действия')),
                ('key_events', models.TextField(blank=True, null=True, verbose_name='Ключевые события')),
                ('most_important_event', models.TextField(blank=True, null=True, verbose_name='Самое главное событие')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Итог')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'На проверке'), (1, 'Одобрен'), (2, 'Отклонен')], verbose_name='Статус одобрения')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Цитата')),
                ('privat', models.BooleanField(default=False, verbose_name='Приватность')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('destination', models.CharField(max_length=200, verbose_name='Куда поделились')),
            ],
            options={
                'ordering': ['-moment'],
            },
        ),
    ]
