# Generated by Django 5.2.5 on 2025-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklog',
            name='privat',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
    ]
