# Generated by Django 5.2.5 on 2025-08-06 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на смену email',
                'verbose_name_plural': 'Запросы на смену email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='account_ema_token_c6b20a_idx'), models.Index(fields=['created_at'], name='account_ema_created_935a93_idx')],
                'unique_together': {('user', 'new_email', 'used')},
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на сброс пароля',
                'verbose_name_plural': 'Запросы на сброс пароля',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='account_pas_token_ca14ea_idx'), models.Index(fields=['created_at'], name='account_pas_created_cfa65a_idx')],
                'unique_together': {('user', 'used')},
            },
        ),
    ]
