# Generated by Django 5.2.4 on 2025-08-04 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='book_logos/', verbose_name='Картинка профиля')),
                ('symbols', models.IntegerField(blank=True, null=True, verbose_name='Количество символов')),
                ('type', models.IntegerField(choices=[(0, 'Художественная'), (1, 'Нон-фикшн (не художественная)')], verbose_name='Тип')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='jornal.author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='jornal.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Начало чтения')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Конец чтения')),
                ('topic', models.TextField(blank=True, null=True, verbose_name='Тема')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('three_sentences', models.TextField(blank=True, null=True, verbose_name='Книга в 3-х предложениях')),
                ('new_knowledge', models.TextField(blank=True, null=True, verbose_name='Новые знания')),
                ('transformed_me', models.TextField(blank=True, null=True, verbose_name='Как книга изменила меня')),
                ('impressions', models.TextField(blank=True, null=True, verbose_name='Впечатления')),
                ('ideas', models.TextField(blank=True, null=True, verbose_name='Основные идеи')),
                ('heroes', models.TextField(blank=True, null=True, verbose_name='Герои')),
                ('begin', models.TextField(blank=True, null=True, verbose_name='Начало действия')),
                ('key_events', models.TextField(blank=True, null=True, verbose_name='Ключевые события')),
                ('most_important_event', models.TextField(blank=True, null=True, verbose_name='Самое главное событие')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Итог')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_logs', to='jornal.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Цитата')),
                ('privat', models.BooleanField(default=False, verbose_name='Приватность')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='jornal.book', verbose_name='Книга')),
                ('book_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='jornal.booklog', verbose_name='Запись читателького журнала')),
                ('likes', models.ManyToManyField(related_name='liked_quotes', through='jornal.Like', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='jornal.quote', verbose_name='Цитата'),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('destination', models.CharField(max_length=200, verbose_name='Куда поделились')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='jornal.quote', verbose_name='Цитата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-moment'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='shared',
            field=models.ManyToManyField(related_name='shared_quotes', through='jornal.Share', to=settings.AUTH_USER_MODEL, verbose_name='Поделились'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'quote')},
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['moment'], name='jornal_shar_moment_e93399_idx'),
        ),
    ]
